### ISSUE TITLE
Implement a contract that resolves an address to an event

### ISSUE THREAD

**Issue by HenryNguyen5** [dinocelotti/Smart-Tickets#4]
In order to efficiently query and resolve an address of an EOA, a resolver contract needs to be created that allows a constant time lookup from a an EOA -> associated event contracts. This will allow solve the problem of polling a users owned addresses and seeing which event contracts they are associated with. From that mapping result, their status as a promoter/buyer/etc can be determined since the event address is now known

**Comment by HenryNguyen5** [comment]
A side effect of this resolver contract in its current implementation is that it is able to keep track of all events a particular address has been associated with, eliminating the need for a centralised solution to take care of this aspect of keeping track of previous events. Could also leverage this in social gamification aspects for showing "History" of past events, and letting the user add friend's addresses which the system could also track between events.

**Comment by dinocelotti** [comment]
You may need to explain this to me a little deeper. 
Also:
- How much control does the user have over whether events are shown or not? aka. A guy and his buds love heavy metal music, so they want to always show off to one another about the concerts they've been to. But one of the guys probably doesn't want his friends to know that he also went to the Britney Spears concert last week. (if you know what I mean). 
- Centralized solution allows for the user to control as opposed to all information being public? 
- Adding friends addresses sounds good, unless we flip that around because it also means that a "stalker" could add people's addresses and know which events they went to. 
Just to clarify, what's an EOA?
